apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-2-deployment
  namespace: todo
  labels:
    app: go-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-2
  template:
    metadata:
      labels:
        app: go-2
    spec:
      containers:
      - name: go-2
        image: shubhamshinde2206/go-2:10139802130
        ports:
        - containerPort: 8086

---

apiVersion: v1
kind: Service
metadata:
  name: go-2-service
  namespace: todo
spec:
  type: ClusterIP 
  selector:
    app: go-2
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086